[workspace]
authors = [""]
channels = ["conda-forge"]
name = "real-robot-inference"
platforms = ["linux-64"]
version = "0.1.0"

[tasks.copy]
args = [
    { arg = "exp_name" },
    { arg = "pattern", default = "*last*" },
]
cmd = "rsync -avz --update --rsync-path='/home/nmarticorena/.pixi/bin/rsync' {{ exp_name }}/{{ pattern }}   nmarticorena@rllab.qut.edu.au:/home/nmarticorena/real-robot-inference/{{ exp_name }}/"

[tasks.sync_datasets]
cmd = "rsync -avz --ignore-existing nmarticorena@rllab.qut.edu.au:/home/nmarticorena/panda_dc/data/ data/"
[tasks.copy_all]
cmd = "echo Copy all weights"
args = [
    { arg = "exp_name" },
]
depends-on = [
    { task = "copy", args = [{pattern = "*.yaml" }, {exp_name = "{{ exp_name }}"}] },
    { task = "copy", args = [{pattern = "*last*" }, {exp_name = "{{ exp_name }}"}] },
    { task = "copy", args = [{pattern = "*.pkl" }, {exp_name = "{{ exp_name }}"}] },
]

[system-requirements]
cuda = "12.8"

[dependencies]
python = "==3.11"
cmake = ">=3.19.0.1"
mujoco = ">=3.3.2,<4"
datasets = ">=4.3.0,<5"
deepdiff = ">=8.6.1,<9"
diffusers = ">=0.35.2,<0.36"
draccus = ">=0.10.0,<0.11"
einops = ">=0.8.1,<0.9"
flask = ">=3.1.2,<4"
gdown = ">=5.2.0,<6"
gymnasium = ">=1.2.1,<2"
h5py = ">=3.15.1,<4"
imageio = ">=2.37.0,<3"
huggingface_hub = ">=1.0.1,<2"
jsonlines = ">=4.0.0,<5"
numba = ">=0.62.1,<0.63"
omegaconf = ">=2.3.0,<3"
av = ">=16.0.1,<17"
pymunk = ">=7.1.0,<8"
pynput = ">=1.8.1,<2"
pyzmq = ">=27.1.0,<28"
termcolor = ">=3.2.0,<4"
wandb = ">=0.22.3,<0.23"
zarr = ">=2.18.3,<3"
pygame = ">=2.6.1,<3"
shapely = ">=2.1.2,<3"
scikit-image = ">=0.25.2,<0.26"
matplotlib = ">=3.10.7,<4"
dm_control = ">=1.0.9,<2"
py-opencv = ">=4.12.0,<5"
libgl = ">=1.7.0,<2"
pytorch-gpu = ">=2.7.1,<3" # https://github.com/conda-forge/torchvision-feedstock/issues/130
cuda-version = "12.9.*"
torchvision = ">=0.24.0,<0.25"
pims = ">=0.7,<0.8"
tyro = ">=0.9.35,<0.10"
hatchling = ">=1.27.0,<2"
pdbpp = ">=0.11.7,<0.12"
reactivex = ">=4.0.4,<5"
pyrealsense2 = {version = ">=2.56.5,<3", build = '*cpu'} # If not pulls the cuda version that does not work with multirealsense, why? I dont know....
eigen = ">=3.4.0,<4"
libfranka = {version = "==0.9.2"}
threadpoolctl = ">=3.6.0,<4"
gxx = "~=9.4"
pybind11-stubgen = ">=2.5.5,<3"
ffmpeg = ">=8.0.0,<9"
scikit-build-core = ">=0.11.6,<0.12"
librealsense = ">=2.56.5,<3"
ipython = ">=9.7.0,<10"
jupyter = ">=1.1.1,<2"
nbstripout = ">=0.8.1,<0.9"

[pypi-options]
no-build-isolation = true

[pypi-dependencies]
huggingface-hub = {extras = ["hf-transfer", "cli"]}
rs_imle_policy = {path = ".", editable = true}
roboticstoolbox-python = {git = "https://github.com/nmarticorena/robotics-toolbox-python.git"}
swift-sim = {git = "https://github.com/nmarticorena/swift.git"}
spatialgeometry = {git = "https://github.com/nmarticorena/spatialgeometry.git"}
spatialmath-python = {git = "https://github.com/nmarticorena/spatialmath-python.git"}
frankx = {git = "https://github.com/nmarticorena/frankx.git"}
atomics = ">=1.0.3, <2"
panda-python = ">=0.8.1, <0.9"
