[workspace]
authors = [""]
channels = ["conda-forge"]
name = "real-robot-inference"
platforms = ["linux-64"]
version = "1.0.0"


[tasks.gripper_home]
cmd = "python3 scripts/robot/home_gripper.py"

[tasks.copy_all]
args = [
    { arg = "exp_name" },
]
cmd = """
rsync -avz  \
    --rsync-path='/home/nmarticorena/.pixi/bin/rsync' \
    --include='*.yaml' \
    --include='*last*' \
    --include='*.pkl' \
    --exclude='*' \
    {{ exp_name }}/ \
    nmarticorena@rllab.qut.edu.au:/home/nmarticorena/real-robot-inference/{{ exp_name }}/
"""

[tasks.sync_datasets]
cmd = "rsync -avz --ignore-existing nmarticorena@rllab.qut.edu.au:/home/nmarticorena/panda_dc/data/ data/"

[system-requirements]
cuda = "12.8"

[dependencies]
python = "==3.11"
cmake = ">=3.19.0.1"
datasets = ">=4.3.0,<5"
deepdiff = ">=8.6.1,<9"
diffusers = ">=0.35.2,<0.36"
draccus = ">=0.10.0,<0.11"
einops = ">=0.8.1,<0.9"
flask = ">=3.1.2,<4"
gdown = ">=5.2.0,<6"
gymnasium = ">=1.2.1,<2"
h5py = ">=3.15.1,<4"
imageio = ">=2.37.0,<3"
huggingface_hub = ">=1.0.1,<2"
jsonlines = ">=4.0.0,<5"
omegaconf = ">=2.3.0,<3"
av = ">=16.0.1,<17"
pymunk = ">=7.1.0,<8"
pynput = ">=1.8.1,<2"
pyzmq = ">=27.1.0,<28"
termcolor = ">=3.2.0,<4"
wandb = ">=0.22.3,<0.23"
zarr = ">=2.18.3,<3"
pygame = ">=2.6.1,<3"
shapely = ">=2.1.2,<3"
scikit-image = ">=0.25.2,<0.26"
matplotlib = ">=3.10.7,<4"
dm_control = ">=1.0.9,<2"
py-opencv = ">=4.12.0,<5"
libgl = ">=1.7.0,<2"
pytorch-gpu = ">=2.7.1,<3" # https://github.com/conda-forge/torchvision-feedstock/issues/130
cuda-version = "12.9.*"
torchvision = ">=0.24.0,<0.25"
pims = ">=0.7,<0.8"
tyro = ">=0.9.35,<0.10"
hatchling = ">=1.27.0,<2"
pdbpp = ">=0.11.7,<0.12"
reactivex = ">=4.0.4,<5"
pyrealsense2 = {version = ">=2.56.5,<3", build = '*cpu'} # If not pulls the cuda version that does not work with multirealsense, why? I dont know....
eigen = ">=3.4.0,<4"
libfranka = {version = "==0.9.2"}
threadpoolctl = ">=3.6.0,<4"
gxx = "~=9.4"
pybind11-stubgen = ">=2.5.5,<3"
ffmpeg = ">=8.0.0,<9"
scikit-build-core = ">=0.11.6,<0.12"
librealsense = ">=2.56.5,<3"
ipython = ">=9.7.0,<10"
jupyter = ">=1.1.1,<2"
nbstripout = ">=0.8.1,<0.9"
inquirerpy = ">=0.3.4,<0.4"
pybind11 = ">=3.0.1,<4"
rerun-sdk = ">=0.27.2,<0.28"
yourdfpy = ">=0.0.57,<0.0.58"
trimesh = ">=4.10.0,<5"
pycollada = ">=0.9.2,<0.10"
numba = ">=0.63.1,<0.64"
grad-cam = ">=1.5.5,<2"
qpsolvers = ">=4.8.2,<5"

[pypi-options]
no-build-isolation = true

[pypi-dependencies]
moviepy = {git = "https://github.com/Zulko/moviepy.git", rev = "7ffa4f00376237137a25fe1c777355c37753e9af"}
huggingface-hub = {extras = ["hf-transfer", "cli"]}
rs_imle_policy = {path = ".", editable = true}
franka-sim = {path = "../libfranka-sim/", editable = true}
roboticstoolbox-python = {git = "https://github.com/nmarticorena/robotics-toolbox-python.git"}
swift-sim = {git = "https://github.com/nmarticorena/swift.git"}
spatialgeometry = {git = "https://github.com/nmarticorena/spatialgeometry.git"}
spatialmath-python = {git = "https://github.com/nmarticorena/spatialmath-python.git"}
frankx = {git = "https://github.com/nmarticorena/frankx.git", rev = "legacy_version"}
atomics = ">=1.0.3, <2"
panda-python = ">=0.8.1, <0.9"

[activation.env]
PANDA_IP = "172.16.0.2"
